python3-pyqt5: Update to 5.15 version
Source: meta-qt5
MR: 109119
Type: Integration
Disposition: Merged from meta-qt5
ChangeID: 7356cd9782b2fef8a46b05b52548ca21738a111a
Description:

5.13 release no longer works with QT 5.15+ since it uses some of removed
interfaces

Fixes
QtQuick/sipQtQuickQSGGeometry.cpp:940:103: error: use of deleted function 'QSGGeometry& QSGGeometry::operator=(const QSGGeometry&)'

Signed-off-by: Khem Raj <raj.khem@gmail.com>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>