conf/layer.conf: Add meta-oe to LAYERDEPENDS
Source: meta-qt5
MR: 139755
Type: Integration
Disposition: Merged from meta-qt5
ChangeID: 644ebf220245bdc06e7696ccc90acc97a0dd2566
Description:

Layer meta-openembedded/meta-oe provides sip. It is required to
avoid errors while building python3-pyqt5 which depends on sip,
for example:

ERROR: Required build target 'python3-pyqt5' has no buildable providers.
Missing or unbuildable dependency chain was: ['python3-pyqt5', 'sip3-native']

Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>
Signed-off-by: Martin Jansa <martin.jansa@gmail.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>