python3-pyqt5: Update to dev2008271829 snapshot
Source: meta-qt5
MR: 109119
Type: Integration
Disposition: Merged from meta-qt5
ChangeID: a7940accda4f9afe122d5d572579af1dc39605d5
Description:

Old version no longer available:

ERROR: python3-pyqt5-5.15.1.dev2008081558-r0 do_fetch: Fetcher failure
for URL: 'https://www.riverbankcomputing.com/static/Downloads/PyQt5/PyQt5-5.15.1.dev2008081558.tar.gz'.
Unable to fetch URL from any source.

Signed-off-by: Daniel Gomez <daniel@qtec.com>
Signed-off-by: Jeremy Puhlman <jpuhlman@mvista.com>