qtbase: add -DUSE_X11 Flag
Source: meta-qt5
MR: 125002
Type: Integration
Disposition: Merged from meta-qt5
ChangeID: f1a3ff4c83de8961366819099e505a5f5152c8e6
Description:

Recently Mesa synced egl headers with khronos.
Until now eglplatform.h added the xlib headers as long as it
hasn't been explicitly disabled with EGL_NO_X11. Now its one step
closer to deprecating X11 and the headers are only included if
USE_X11 is set. If missing qtbase silently refuses to build the EGL_X11
Plugin.

This results e.g. in configure failure for qtwayland, if building
with xcomposite-egl PACKAGECONFIG:

ERROR: Feature 'xcomposite-egl' was enabled, but the pre-condition
'features.wayland-client && features.opengl && features.egl && features.xlib
&& libs.xcomposite && features.egl_x11' failed.

Signed-off-by: Markus Volk <f_l_k@t-online.de>
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
Signed-off-by: Jeremy A. Puhlman <jpuhlman@mvista.com>